swagger: '2.0'
info:
  version: '1.0.0'
  title: 'Company API'
definitions:
  Company:
    type: 'object'
    properties:
      name:
        type: 'string'
        pattern: '^(?!\s*$).+'
    required:
      - name
